import crypto from 'node:crypto';
import { transforms, color, dedent, defineEnv } from '@sveltejs/sv-utils';
import { defineAddon, defineAddonOptions } from 'sv';

const options = defineAddonOptions()
	.add('admin', {
		question: 'Include the Better Auth admin plugin?',
		type: 'boolean',
		default: true
	})
	.add('demo', {
		question: 'Which demo would you like to include?',
		type: 'multiselect',
		default: ['password'],
		options: [
			{ value: 'password', label: 'Email & Password' },
			{ value: 'github', label: 'GitHub OAuth' }
		],
		required: false
	})
	.build();

export default defineAddon({
	id: 'better-auth-prisma',
	shortDescription: 'Better Auth with Prisma adapter',
	homepage: 'https://www.better-auth.com',
	options,
	setup: ({ isKit, unsupported, dependsOn, dependencyVersion, runsAfter }) => {
		if (!isKit) unsupported('Requires SvelteKit');
		if (!dependencyVersion('prisma')) dependsOn('prisma');
		runsAfter('prisma');
		runsAfter('sveltekitAdapter');
		runsAfter('tailwindcss');
	},
	run: ({ sv, options, language, file, directory, dependencyVersion }) => {
		const demoPassword = options.demo.includes('password');
		const demoGithub = options.demo.includes('github');
		const hasDemo = demoPassword || demoGithub;

		const env = defineEnv({ sv, cwd: process.cwd(), dependencyVersion });

		env.define({
			name: 'ORIGIN',
			description: 'The app origin (base URL), e.g. `http://localhost:5173`.'
		});
		env.define({
			name: 'BETTER_AUTH_SECRET',
			description:
				'Secret used to sign tokens. For production use 32 characters generated with high entropy.'
		});
		if (demoGithub) {
			env.define({
				name: 'GITHUB_CLIENT_ID',
				description: 'GitHub OAuth client ID.'
			});
			env.define({
				name: 'GITHUB_CLIENT_SECRET',
				description: 'GitHub OAuth client secret.'
			});
		}

		sv.devDependency('better-auth', '^1.6.23');
		sv.dependency('@better-auth/prisma-adapter', '^1.6.23');

		sv.file('.env', generateEnv(demoGithub, false));
		sv.file('.env.example', generateEnv(demoGithub, true));

		const authConfigPath = `${directory.lib}/server/auth.${language}`;
		const authSchemaPath = `${directory.lib}/server/db/auth.schema.${language}`;
		const dbPath = `${directory.lib}/server/db.${language}`;

		sv.file(
			authConfigPath,
			transforms.text(({ content }) => {
				if (content) return false;
				const adminPlugin = options.admin
					? `\nimport { admin as adminPlugin } from "better-auth/plugins";`
					: '';
				const adminConfig = options.admin
					? `
						plugins: [
							adminPlugin(),
							sveltekitCookies(getRequestEvent)
						],`
					: `
						plugins: [
							sveltekitCookies(getRequestEvent)
						],`;

				return dedent`
					import { betterAuth } from "better-auth";
					import { prismaAdapter } from "better-auth/adapters/prisma";
					import { sveltekitCookies } from "better-auth/svelte-kit";${adminPlugin}
					import { getRequestEvent } from "$app/server";
					import { prisma } from "${dbPath.replace(`.${language}`, '')}";

					export const auth = betterAuth({
						database: prismaAdapter(prisma, {
							provider: "${dependencyVersion('prisma') ? 'postgresql' : 'postgresql'}"
						}),
						emailAndPassword: {
							enabled: true
						},${adminConfig}
					});
				`;
			})
		);

		sv.file(
			authSchemaPath,
			transforms.text(({ content }) => {
				if (content) return false;
				return dedent`
					// Run the auth:schema script to generate the auth tables
					// This file will be overwritten with the actual schema
					export {};
				`;
			})
		);

		sv.file(
			`${directory.lib}/server/db/auth.schema.${language}`,
			transforms.text(({ content }) => {
				if (content) return false;
				return dedent`
					// Better Auth schema - will be generated by auth:schema script
					// Run: npm run auth:schema
					export {};
				`;
			})
		);

		sv.file(
			file.package,
			transforms.json(({ data, json }) => {
				json.packageScriptsUpsert(
					data,
					'auth:schema',
					`auth generate --config ${authConfigPath} --output ${authSchemaPath} --yes`
				);
			})
		);

		sv.file(
			'src/app.d.ts',
			transforms.script(({ ast, comments, js }) => {
				js.imports.addNamed(ast, {
					imports: ['User', 'Session'],
					from: 'better-auth',
					isType: true
				});

				const locals = js.kit.addGlobalAppInterface(ast, { name: 'Locals' });
				if (!locals) {
					throw new Error('Failed detecting `locals` interface in `src/app.d.ts`');
				}

				comments.remove((c) => c.type === 'Line' && c.value.trim() === 'interface Locals {}');

				const user = locals.body.body.find((prop) =>
					js.common.hasTypeProperty(prop, { name: 'user' })
				);
				const session = locals.body.body.find((prop) =>
					js.common.hasTypeProperty(prop, { name: 'session' })
				);

				if (!user) {
					locals.body.body.push(js.common.createTypeProperty('user', 'User', true));
				}
				if (!session) {
					locals.body.body.push(js.common.createTypeProperty('session', 'Session', true));
				}
			})
		);

		sv.file(
			`src/hooks.server.${language}`,
			transforms.script(({ ast, comments, js }) => {
				js.imports.addNamed(ast, {
					imports: ['svelteKitHandler'],
					from: 'better-auth/svelte-kit'
				});
				js.imports.addNamed(ast, {
					imports: ['auth'],
					from: `${directory.lib.replace('src/', '$lib/')}/server/auth`
				});
				env.importEnv(ast, js, ['building']);

				const handleContent = dedent`
				async ({ event, resolve }) => {
					const session = await auth.api.getSession({
						headers: event.request.headers
					});
					if (session) {
						event.locals.session = session.session;
						event.locals.user = session.user;
					}
					return svelteKitHandler({ event, resolve, auth, building });
				};

				export const handle = sequence(handleBetterAuth, handleSession);
			`;
				js.kit.addHooksHandle(ast, {
					language,
					newHandleName: 'handleBetterAuth',
					handleContent,
					comments
				});
			})
		);

		if (hasDemo) {
			sv.file(
				`${directory.kitRoutes}/demo/better-auth/login/+page.server.${language}`,
				(content) => {
					if (content) return false;
					const signInEmailAction = demoPassword
						? `
						signInEmail: async (event) => {
							const formData = await event.request.formData();
							const email = formData.get('email')?.toString() ?? '';
							const password = formData.get('password')?.toString() ?? '';

							try {
								await auth.api.signInEmail({
									body: {
										email,
										password,
										callbackURL: '/auth/verification-success'
									}
								});
							} catch (error) {
								if (error instanceof APIError) {
									return fail(400, { message: error.message || 'Signin failed' });
								}
								return fail(500, { message: 'Unexpected error' });
							}

							return redirect(302, '/demo/better-auth');
						},
						signUpEmail: async (event) => {
							const formData = await event.request.formData();
							const email = formData.get('email')?.toString() ?? '';
							const password = formData.get('password')?.toString() ?? '';
							const name = formData.get('name')?.toString() ?? '';

							try {
								await auth.api.signUpEmail({
									body: {
										email,
										password,
										name,
										callbackURL: '/auth/verification-success'
									}
								});
							} catch (error) {
								if (error instanceof APIError) {
									return fail(400, { message: error.message || 'Registration failed' });
								}
								return fail(500, { message: 'Unexpected error' });
							}

							return redirect(302, '/demo/better-auth');
						},`
						: '';

					const signInSocialAction = demoGithub
						? `
						signInSocial: async (event) => {
							const formData = await event.request.formData();
							const provider = formData.get('provider')?.toString() ?? 'github';
							const callbackURL = formData.get('callbackURL')?.toString() ?? '/demo/better-auth';

							const result = await auth.api.signInSocial({
								body: {
									provider: provider as "github",
									callbackURL
								}
							});

							if (result.url) {
								return redirect(302, result.url);
							}
							return fail(400, { message: 'Social sign-in failed' });
						},`
						: '';

					return dedent`
						import { fail, redirect } from '@sveltejs/kit';
						import type { Actions } from './$types';
						import type { PageServerLoad } from './$types';
						import { auth } from '$lib/server/auth';
						import { APIError } from 'better-auth/api';

						export const load: PageServerLoad = (event) => {
							if (event.locals.user) {
								return redirect(302, '/demo/better-auth');
							}
							return {};
						};

						export const actions: Actions = {${signInEmailAction}${signInSocialAction}
						};
					`;
				}
			);

			sv.file(`${directory.kitRoutes}/demo/better-auth/login/+page.svelte`, (content) => {
				if (content) return false;
				return dedent`
					<script lang="ts">
						import { enhance } from '$app/forms';
						import type { ActionData } from './$types';

						let { form }$<{ form: ActionData } = $props();
					</script>

					<h1>Login</h1>

					<form method="post" action="?/signInEmail" use:enhance>
						<label>
							Email
							<input type="email" name="email" />
						</label>
						<label>
							Password
							<input type="password" name="password" />
						</label>
						<label>
							Name (for registration)
							<input name="name" />
						</label>
						<button>Login</button>
						<button formaction="?/signUpEmail">Register</button>
					</form>

					<p style="color: red">{form?.message ?? ''}</p>
				`;
			});

			sv.file(`${directory.kitRoutes}/demo/better-auth/+page.server.${language}`, (content) => {
				if (content) return false;
				return dedent`
					import { redirect } from '@sveltejs/kit';
					import type { Actions } from './$types';
					import type { PageServerLoad } from './$types';
					import { auth } from '$lib/server/auth';

					export const load: PageServerLoad = (event) => {
						if (!event.locals.user) {
							return redirect(302, '/demo/better-auth/login');
						}
						return { user: event.locals.user };
					};

					export const actions: Actions = {
						signOut: async (event) => {
							await auth.api.signOut({
								headers: event.request.headers
							});
							return redirect(302, '/demo/better-auth/login');
						}
					};
				`;
			});

			sv.file(`${directory.kitRoutes}/demo/better-auth/+page.svelte`, (content) => {
				if (content) return false;
				return dedent`
					<script lang="ts">
						import { enhance } from '$app/forms';
						import type { PageServerData } from './$types';

						let { data }$<{ data: PageServerData } = $props();
					</script>

					<h1>Hi, {data.user.name}!</h1>
					<p>Your user ID is {data.user.id}.</p>
					<form method="post" action="?/signOut" use:enhance>
						<button>Sign out</button>
					</form>
				`;
			});
		}
	},
	nextSteps: ({ options, packageManager }) => {
		const steps = [
			`Run ${color.command(resolveCommandArray(packageManager, 'run', ['auth:schema']))} to generate the auth schema`,
			`Run ${color.command(resolveCommandArray(packageManager, 'run', ['db:push']))} to update your database`,
			`Check ${color.env('ORIGIN')} & ${color.env('BETTER_AUTH_SECRET')} in ${color.path('.env')}`
		];
		if (options.demo.includes('github')) {
			steps.push(
				`Set your ${color.env('GITHUB_CLIENT_ID')} and ${color.env('GITHUB_CLIENT_SECRET')} in ${color.path('.env')}`
			);
		}
		if (options.demo.length > 0) {
			steps.push(`Visit ${color.route('/demo/better-auth')} route to view the demo`);
		}
		return steps;
	}
});

function resolveCommandArray(packageManager: string, cmd: string, args: string[]): string {
	const prefix = packageManager === 'npm' ? 'npx' : packageManager === 'pnpm' ? 'pnpm' : 'yarn';
	return `${prefix} ${cmd} ${args.join(' ')}`;
}

type GenerateEnv = (demoGithub: boolean, isExample: boolean) => (content: string) => string;
const generateEnv: GenerateEnv = (demoGithub, isExample) => (content) => {
	const text = content || '';
	const lines = text.split('\n');

	const upsert = (key: string, value: string, comment?: string) => {
		const idx = lines.findIndex((l) => l.startsWith(`${key}=`));
		if (idx === -1) {
			if (comment) lines.push(`# ${comment}`);
			lines.push(`${key}=${value}`);
		}
	};

	upsert('ORIGIN', isExample ? '""' : '"http://localhost:5173"', 'App origin');
	upsert(
		'BETTER_AUTH_SECRET',
		isExample ? '""' : `"${crypto.randomUUID()}"`,
		'Better Auth secret - use 32+ chars in production'
	);

	if (demoGithub) {
		upsert('GITHUB_CLIENT_ID', '""', 'GitHub OAuth');
		upsert('GITHUB_CLIENT_SECRET', '""');
	}

	return lines.join('\n');
};
